### ISSUE TITLE
Possible false-positive.

### ISSUE THREAD

**Issue by NotCreativeBush** [Zalexanninev15/Jetpack-Downgrader#10]
Possible false-positive detection of jdp.exe as a trojan by windows defender.

**Comment by NotCreativeBush** [comment]
Trojan:Win32/Zpevdo.B to be more precise.

**Comment by NotCreativeBush** [comment]
If it is helpful, JDP.zip is being stopped from downloading by windows defender, while JDP_full_offline.zip and JDP_with_patches.zip isn't, though it may just be flagging it as a familiar item cause JDP.zip is the first one i tried.

**Comment by Zalexanninev15** [comment]
Hi, I can't check the code yet, but I have an assumption that it's either gui or a new patching process (I don't exclude the possibility of a problem in patcher.exe), or, extremely unlikely, in new patches. The code is open, you can try to find the problem, I will not be able to search until July 29-30.

**Comment by Zalexanninev15** [comment]
Good day, I'm conducting a search...

**Comment by Zalexanninev15** [comment]
I looked, thought, came to a conclusion. Everything follows the rules of the programming language and the Windows system, which means there are no problems. Antiviruses just make shortcuts, because they don't have any sources. Maybe over time they will lag behind the project.

**Comment by Zalexanninev15** [comment]
May have solved the problem.
jpd.exe: https://www.virustotal.com/gui/file/42322e5a6fdd8c6d8ea469ec6858751a2e2dd5d5627d09374013938e4a3366e9/detection
app.exe: https://www.virustotal.com/gui/file/aeb5f75b1f665e98fc642bf22f6c2fce704785d9eb53f7a27e436316edbfed9e/detection

**Comment by Zalexanninev15** [comment]
Release with fix "false": https://github.com/Zalexanninev15/Jetpack-Downgrader/releases/tag/2.2
