### ISSUE TITLE
Looking for localizers

### ISSUE THREAD

**Issue by Zalexanninev15** [Zalexanninev15/Jetpack-Downgrader#17]
At the moment, English and Russian localization are ready. General guide for editing and adding localization in the GUI: https://github.com/Zalexanninev15/Jetpack-Downgrader/blob/unstable/data/docs/AddNewData.md#add-new-localizations

**Comment by TheKreator666** [comment]
[HR.zip](https://github.com/Zalexanninev15/Jetpack-Downgrader/files/9997577/HR.zip)
Croatian translation for the downgrader, which was thoroughly tested and is working correctly.

**Comment by Zalexanninev15** [comment]
> [HR.zip](https://github.com/Zalexanninev15/Jetpack-Downgrader/files/9997577/HR.zip) Croatian translation for the downgrader, which was thoroughly tested and is working correctly.

Thank you for localization, but the project has been frozen since 2021 after the release of the *updated* trilogy of games. I don't know if it makes sense to make a new version. And I'm not sure that the downgrader is working stably. Have you tested this process on the game?

**Comment by TheKreator666** [comment]
I tried using the downgrader itself, and I gotta admit, this is probably one of the easiest ones to use so far, didn't have any issues whatsoever and the game is working fine.

Thank you for taking your time and adding the translation for manual installation

**Comment by Zalexanninev15** [comment]
> I tried using the downgrader itself, and I gotta admit, this is probably one of the easiest ones to use so far, didn't have any issues whatsoever and the game is working fine.
> 
> Thank you for taking your time and adding the translation for manual installation

That's awesome. Thank you again for the localization. May I ask how exactly you found out about the project?

**Comment by TheKreator666** [comment]
> > I tried using the downgrader itself, and I gotta admit, this is probably one of the easiest ones to use so far, didn't have any issues whatsoever and the game is working fine.
> > Thank you for taking your time and adding the translation for manual installation
> 
> That's awesome. Thank you again for the localization. May I ask how exactly you found out about the project?

Of course. I actually found it via GTA Forums as I wanted to play GTA SA again, and I really like what you did with the project so far. It's amazing, tbh, and the ability to add more mods before the downgrade is a nice addition.
